config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :cards
  end

  root "boards#index"
  get "about" => "pages#about"
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :cards
  accepts_nested_attributes_for :cards
  
  before_validation :generate_slug

  def to_param
    slug
  end
  
  def generate_slug
    self.slug ||= SecureRandom.base64(8) if name
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :board
  before_save :default_values  
  POSITION = %w(backlog doing done)
  
  private
  
  def default_values
    self.position ||= "backlog"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @board = Board.new
  end

  def show
    @cards = @board.cards
    @backlog = @board.cards.where(position: "backlog")
    @doing = @board.cards.where(position: "doing")
    @done = @board.cards.where(position: "done")
  end

  def new
    @board = Board.new
  end

  def edit
  end


  def create
    @board = Board.new(board_params)
    
    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created. Share it!' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'This is your board. Now share it!' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
    end
  end

  private
  
    def set_board
      @board = Board.find_by(slug: params[:id])
    end

    def board_params
      params.require(:board).permit(:name, :card)
    end
    
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_board
  
  def index
    @cards = @board.cards
  end
  
  def new
    @card = @board.cards.new
  end
  
  def create
    @card = @board.cards.create!(card_params)
    respond_to do |format|
      format.html { redirect_to board_path }
      format.js
    end
  end
  
  def update
    @card = @board.cards.find(params[:id])
    @card.update_attributes!(params[:card])
    respond_to do |format|
      format.html { redirect_to board_path }
      format.js
    end
  end
  
  
  def destroy
    @card = @board.cards.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to board_path }
      format.js
    end
  end
  
  
  private
  
  def card_params
    params.require(:card).permit(:name)
  end
  
  def set_board
    @board = Board.find_by!(slug: params[:board_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="jumbotron center">
<h3>Change name of board</h3>

<%= render 'form' %>

<%= link_to 'Go back to the board', @board %> |
<%= link_to 'Back', boards_path %>
</div>

app/views/boards/index.html.erb
<div class="jumbotron center">
<h1>Welcome to QuickBoard!</h1>
<p class="lead">
	Need a quick task board to share? Create it. Share it. Boom!
</p>

<%= render 'form' %>
</div>

app/views/boards/new.html.erb
<div class="jumbotron center">
<h3>Create new board</h3>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>
</div>

app/views/boards/show.html.erb
<div class="jumbotron center"><p>
  <h2><%= @board.name %></h2>
</p>

<div class"row">



<%= link_to "Add Card", new_board_card_path(@board),
								id: "new_link",
								remote: true,
                class: "btn btn-default btn-lg"  %>

</div>
	<div class="row">
		<div class="col-sm-4">
				<h3>Backlog</h3>
				<% @backlog.each do |card| %>

				<div class="panel panel-default" draggable="true" ondragstart="drag(event)" id="drag1">
				  <div class="panel-body">
				    <p><%= card.name %></p>
						<%= link_to 'remove', [@board, card], method: :delete, data: {confirm: "Are you sure?"} %>

				  </div>
				</div>

				<% end %>
		</div>

		<div class="col-sm-4">
				<h3>Doing</h3>
				<% @doing.each do |card| %>

				<div class="panel panel-default" draggable="true" ondragstart="drag(event)" id="drag1">
				  <div class="panel-body">
				    <p><%= card.name %></p>
						Edit <%= link_to 'Destroy', [@board, card], method: :delete %>
				  </div>
				</div>

				<% end %>

		</div>



		<div class="col-sm-4">
				<h3>Done</h3>
				<% @done.each do |card| %>

				<div class="panel panel-default">
				  <div class="panel-body">
				    <%= card.name %>
				  </div>
				</div>

				<% end %>
		</div>

</div>

<%= link_to 'Change name of this board', edit_board_path(@board) %> | <%= link_to 'Create new board', new_board_path %>

app/views/cards/_card.html.erb
<%= form_for [@board, @card], remote: true do |f| %>


	<div class="panel panel-default">
	  	<div class="panel-body">

  <p><%= card.name %></p>


	<%= link_to "remove", [@board, @card], method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
</div>
</div>

<% end %>

app/views/cards/_form.html.erb
<%= form_for [@board, @card], remote: true do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/cards/index.html.erb
<header id="content-header">
  <h1>Cardsfor <%= link_to(@board.name, @board) %></h2>
</header>


  <% @cards.each do |card| %>
    <div class="panel panel-default">
      <%= card.name %>

		</div>
  <% end %>

app/views/cards/new.html.erb
<div class="jumbotron center">
<h3>Create new card</h3>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quickboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our app!</p>